openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
  description: API for managing tasks and subtasks
paths:
  /tasks/{username}:
    get:
      summary: Get all tasks for a user
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '404':
          description: User not found
        '500':
          description: Internal server error
  /tasks:
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - subject
                - deadline
                - status
              properties:
                username:
                  type: string
                subject:
                  type: string
                deadline:
                  type: string
                  format: date
                status:
                  type: string
                subtasks:
                  type: array
                  items:
                    $ref: '#/components/schemas/Subtask'
      responses:
        '201':
          description: Task created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '500':
          description: Internal server error
  /tasks/{taskId}:
    put:
      summary: Update a task
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - subject
                - deadline
                - status
              properties:
                subject:
                  type: string
                deadline:
                  type: string
                  format: date
                status:
                  type: string
      responses:
        '200':
          description: Task updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: User or task not found
        '500':
          description: Internal server error
    delete:
      summary: Soft delete a task
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task soft deleted
        '404':
          description: User or task not found
        '500':
          description: Internal server error
  /tasks/{taskId}/subtasks:
    get:
      summary: Get all subtasks for a task
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of subtasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subtask'
        '404':
          description: User or task not found
        '500':
          description: Internal server error
    put:
      summary: Update multiple subtasks for a task
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - subtasks
              properties:
                subtasks:
                  type: array
                  items:
                    $ref: '#/components/schemas/Subtask'
      responses:
        '200':
          description: Subtasks updated
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subtask'
        '404':
          description: User or task not found
        '500':
          description: Internal server error
components:
  schemas:
    Task:
      type: object
      required:
        - subject
        - deadline
        - status
      properties:
        _id:
          type: string
        subject:
          type: string
        deadline:
          type: string
          format: date
        status:
          type: string
        subtasks:
          type: array
          items:
            $ref: '#/components/schemas/Subtask'
        deleted:
          type: boolean
    Subtask:
      type: object
      required:
        - subject
        - deadline
        - status
      properties:
        _id:
          type: string
        subject:
          type: string
        deadline:
          type: string
          format: date
        status:
          type: string
        deleted:
          type: boolean
